name: pymc-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - pytensor
    - pyfastx
    - umi_tools
    - numpy
    - pandas
    - scipy
    - matplotlib
